### PR TITLE
Cmssw 10 0 0 pre3

### LINKED ISSUE #20: CMSSW 10_0_0_pre3 update
Update the framework to be compatible with CMSSW [10_0_0_pre3](https://github.com/cms-sw/cmssw/tree/CMSSW_10_0_0_pre2) release.

This requires extensive modifications following this [PR](https://github.com/cms-sw/cmssw/pull/21685).

### PR DESCRIPTION
**Pull request by demarley**
Updates for `10_0_0_pre3`.  There were extensive updates, detailed [here](https://github.com/cms-sw/cmssw/compare/CMSSW_10_0_0_pre2...CMSSW_10_0_0_pre3), with numerous updates to the classes in Alignment.  
Edit: Closes #20

### CODE REVIEW

**Comment by demarley** [comment]
There are still lots of differences in formatting with respect to the [CMSSW version](https://github.com/cms-sw/cmssw/blob/CMSSW_10_0_0_pre3/Alignment/MuonAlignmentAlgorithms/plugins/MuonAlignmentFromReference.cc).  
@lpernie I'm not sure if it is necessary to get all of those updates right now, it would be quite tedious.  Hopefully there aren't any algorithm differences -- it should just be formatting.

**Comment by lpernie** [comment]
So what is you suggestion?
We are not in a rush to merge it now, it you thing more time is needed. Also, we could do it in 2 bunches. Something is missing still?

**Comment by demarley** [comment]
Nothing is missing from this commit -- the code has been properly updated.  However, the file "MuonAlignmentAlgorithms/plugins/MuonAlignmentFromReference.cc" has lots of formatting changes in the official CMSSW version.  Our version doesn't reflect all of these, yet, so there are lots of differences (that aren't necessarily real).
I am happy to implement those later, but won't be able to do it with this PR.

**Comment by lpernie** [comment]
Ok, so should I approve this, and the next step is to make the final branch where MuonAlignmentFromReference is also fixed? We heavily modified MuonAlignmentFromReference, so we should carefull there.

**Comment by demarley** [comment]
Yes, if you're okay with it, I would prefer to merge this request now.  Later, when I have time, I can modify the formatting of `MuonAlignmentFromReference` in a later PR.  The fix can come in this branch `10_0_0_pre3` or we can just incorporate it in `10_0_0`.

**Pull request merged**
